AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  environment-variables-example

  Sample SAM Template for environment-variables-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          MY_GLOBAL_VARIABLE: Environment variable 1

Resources:
  EnvironmentVariablesExampleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: EnvironmentVariablesExample
      Handler: com.appsdeveloperblog.aws.lambda.EnvironmentVariablesExample::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          MY_VARIABLE: Environment variable 1
          MY_COGNITO_USER_POOL_ID: ABC1234
          MY_COGNITO_CLIENT_APP_SECRET: SADASDASC
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EnvironmentVariablesExampleApi:
    Description: "API Gateway endpoint URL for Prod stage for EnvironmentVariablesExample function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EnvironmentVariablesExampleFunction:
    Description: "EnvironmentVariablesExample Lambda Function ARN"
    Value: !GetAtt EnvironmentVariablesExampleFunction.Arn
  EnvironmentVariablesExampleFunctionIamRole:
    Description: "Implicit IAM Role created for EnvironmentVariablesExample function"
    Value: !GetAtt EnvironmentVariablesExampleFunctionRole.Arn
